FLAGS =  -I./headers -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE
OBJECTS = main.o clear.o input.o output.o solve.o solveCom.o unit_test.o
SOURCE_DIR = source/
OBJECTS_DIR = objects/

all: square

square: $(OBJECTS)
	g++ $(FLAGS) $(OBJECTS) -o square

main.o: $(SOURCE_DIR)main.cpp
	g++ $(FLAGS) -c source/main.cpp -o main.o

clear.o: $(SOURCE_DIR)clear.cpp
	g++ $(FLAGS) -c @< -o @a

input.o: $(SOURCE_DIR)input.cpp
	g++ $(FLAGS) -c @< -o @a

output.o: $(SOURCE_DIR)output.cpp
	g++ $(FLAGS) -c @< -o @a

solve.o: $(SOURCE_DIR)solve.cpp
	g++ $(FLAGS) -c @< -o @a

solveCom.o: $(SOURCE_DIR)solveCom.cpp
	g++ $(FLAGS) -c @< -o @a

unit_test.o: $(SOURCE_DIR)unit_test.cpp
	g++ $(FLAGS) -c @< -o @a
