FLAGS =  -I./headers -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE
OBJECTS = main.o clear.o input.o output.o solve.o solveCom.o unit_test.o solveFile.o
SOURCE_DIR = source/
OBJECTS_DIR = objects/

all: square

square: $(OBJECTS)
	g++ $(FLAGS) $(OBJECTS) -o square

%.o: $(SOURCE_DIR)%.cpp
	g++ $(FLAGS) -c $< -o $@

clean:
	del -f *.o square

# Замена строк и универсальные правила make
